import EnchantType from "./EnchantType.js";
import MaterialType from "./MaterialType.js";

// /**
//  * xxx
//  * @param {Object} enchantProperty - 属性配置对象
//  * @param {Object} enchantProperty.enchantType - 属性类型
//  * @param {string} enchantProperty.nameChsFull - 中文全名
//  * @param {string} enchantProperty.nameChsAbbr - 中文简称
//  * @param {string} enchantProperty.nameEnFull - 英文全名
//  * @param {string} enchantProperty.nameEnAbbr - 英文简称
//  * @param {number} enchantProperty.isPercentage - 是否有百分号
//  * @param {number} enchantProperty.isNegativePossible - 是否允许负数
//  * @param {number} enchantProperty.upperLimitIncreaseInterval - 超过200版本多少级增长一次，如果不增长填null
//  * @param {number} enchantProperty.lowerLimitIncreaseInterval - 同上，负方向
//  * @param {number} enchantProperty.attenuationThreshold - 衰减阈值
//  * @param {number} enchantProperty.basePotentialCost - 基础耗潜
//  * @param {boolean} enchantProperty.isWeaponDoublePotential - 是否武器双倍耗潜
//  * @param {boolean} enchantProperty.isArmorDoublePotential - 是否防具双倍耗潜
//  * @param {number} enchantProperty.preAttenuationIncrement - 衰减阈值前增长
//  * @param {number} enchantProperty.postAttenuationIncrement - 衰减阈值后增长
//  * @param {number} enchantProperty.baseMaterialCost - 基础耗材
//  * @param {Object} enchantProperty.materialType - 消耗材料类型
//  * @param {Object|null} enchantProperty.cyteriaMapping - 布偶的魔法书属性映射，{base: string, type: 0|1} 或 null
//  */
export default class EnchantProperties {
    static getProperties() {
        return {
            Str: {
                id: "Str",
                idx: 0,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "力量",
                nameChsAbbr: "力量",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "str", type: 0 }, // 布偶中没有对应属性
            },
            StrRate: {
                id: "StrRate",
                idx: 1,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "力量",
                nameChsAbbr: "力量",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "str", type: 1 },
            },
            Int: {
                id: "Int",
                idx: 2,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "智力",
                nameChsAbbr: "智力",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "int", type: 0 },
            },
            IntRate: {
                id: "IntRate",
                idx: 3,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "智力",
                nameChsAbbr: "智力",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "int", type: 1 },
            },
            Vit: {
                id: "Vit",
                idx: 4,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "耐力",
                nameChsAbbr: "耐力",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "vit", type: 0 },
            },
            VitRate: {
                id: "VitRate",
                idx: 5,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "耐力",
                nameChsAbbr: "耐力",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "vit", type: 1 },
            },
            Agi: {
                id: "Agi",
                idx: 6,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "敏捷",
                nameChsAbbr: "敏捷",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "agi", type: 0 },
            },
            AgiRate: {
                id: "AgiRate",
                idx: 7,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "敏捷",
                nameChsAbbr: "敏捷",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "agi", type: 1 },
            },
            Dex: {
                id: "Dex",
                idx: 8,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "灵巧",
                nameChsAbbr: "灵巧",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "dex", type: 0 },
            },
            DexRate: {
                id: "DexRate",
                idx: 9,
                enchantType: EnchantType.ENCHANT_TYPE_ABILITY,
                nameChsFull: "灵巧",
                nameChsAbbr: "灵巧",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "dex", type: 1 },
            },
            HpRecovery: {
                id: "HpRecovery",
                idx: 10,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "体力自然回复",
                nameChsAbbr: "HP回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "natural_hp_regen", type: 0 },
            },
            HpRecoveryRate: {
                id: "HpRecoveryRate",
                idx: 11,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "体力自然回复",
                nameChsAbbr: "HP回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "natural_hp_regen", type: 1 },
            },
            MpRecovery: {
                id: "MpRecovery",
                idx: 12,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "魔法自然回复",
                nameChsAbbr: "MP回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 20,
                lowerLimitIncreaseInterval: 20,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "natural_mp_regen", type: 0 },
            },
            MpRecoveryRate: {
                id: "MpRecoveryRate",
                idx: 13,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "魔法自然回复",
                nameChsAbbr: "MP回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "natural_mp_regen", type: 1 },
            },
            MaxHp: {
                id: "MaxHp",
                idx: 14,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "体力值上限",
                nameChsAbbr: "HP",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 10,
                postAttenuationIncrement: 160,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "max_hp", type: 0 },
            },
            MaxHpRate: {
                id: "MaxHpRate",
                idx: 15,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "体力值上限",
                nameChsAbbr: "HP",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "max_hp", type: 1 },
            },
            MaxMp: {
                id: "MaxMp",
                idx: 16,
                enchantType: EnchantType.ENCHANT_TYPE_HPMP,
                nameChsFull: "魔法值上限",
                nameChsAbbr: "MP",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 20,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 15,
                basePotentialCost: 6,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 10,
                postAttenuationIncrement: 10,
                baseMaterialCost: 33.5,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "max_mp", type: 0 },
            },
            Atk: {
                id: "Atk",
                idx: 17,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "物理攻击",
                nameChsAbbr: "物攻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "攻击力, 攻击加成, 攻击力加成",
                cyteriaMapping: { base: "atk", type: 0 },
            },
            AtkRate: {
                id: "AtkRate",
                idx: 18,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "物理攻击",
                nameChsAbbr: "物攻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 20,
                lowerLimitIncreaseInterval: 20,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "atk", type: 1 },
            },
            Matk: {
                id: "Matk",
                idx: 19,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "魔法攻击",
                nameChsAbbr: "魔攻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "matk", type: 0 },
            },
            MatkRate: {
                id: "MatkRate",
                idx: 20,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "魔法攻击",
                nameChsAbbr: "魔攻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 20,
                lowerLimitIncreaseInterval: 20,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "matk", type: 1 },
            },
            Sta: {
                id: "Sta",
                idx: 21,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "稳定率",
                nameChsAbbr: "稳定",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "stability", type: 0 },
            },
            DefBreaker: {
                id: "DefBreaker",
                idx: 22,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "物理贯穿",
                nameChsAbbr: "物贯",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 25,
                lowerLimitIncreaseInterval: 25,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "physical_pierce", type: 0 },
            },
            MdefBreaker: {
                id: "MdefBreaker",
                idx: 23,
                enchantType: EnchantType.ENCHANT_TYPE_ATK,
                nameChsFull: "魔法贯穿",
                nameChsAbbr: "魔贯",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 25,
                lowerLimitIncreaseInterval: 25,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "magic_pierce", type: 0 },
            },
            Def: {
                id: "Def",
                idx: 24,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "物理防御",
                nameChsAbbr: "物防",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 10,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "def", type: 0 },
            },
            DefRate: {
                id: "DefRate",
                idx: 25,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "物理防御",
                nameChsAbbr: "物防",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "def", type: 1 },
            },
            Mdef: {
                id: "Mdef",
                idx: 26,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "魔法防御",
                nameChsAbbr: "魔防",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 10,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "mdef", type: 0 },
            },
            MdefRate: {
                id: "MdefRate",
                idx: 27,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "魔法防御",
                nameChsAbbr: "魔防",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "mdef", type: 1 },
            },
            PowerResist: {
                id: "PowerResist",
                idx: 28,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "物理抗性",
                nameChsAbbr: "物抗",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "physical_resistance", type: 0 },
            },
            MagicResist: {
                id: "MagicResist",
                idx: 29,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "魔法抗性",
                nameChsAbbr: "魔抗",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "magic_resistance", type: 0 },
            },
            SurroundingsResist: {
                id: "SurroundingsResist",
                idx: 30,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "敌方周围伤害减轻",
                nameChsAbbr: "敌方周围减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 6,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 15,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_foe_epicenter", type: 0 },
            },
            RangeResist: {
                id: "RangeResist",
                idx: 31,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "范围伤害减轻",
                nameChsAbbr: "范围减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 6,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 15,
                materialType: MaterialType.MATERIAL_TYPE_METAL,
                description: "",
                cyteriaMapping: { base: "reduce_player_epicenter", type: 0 },
            },
            LineResist: {
                id: "LineResist",
                idx: 32,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "直线伤害减轻",
                nameChsAbbr: "直线减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 6,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 15,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_straight_line", type: 0 },
            },
            MoveAttackResist: {
                id: "MoveAttackResist",
                idx: 33,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "冲撞伤害减轻",
                nameChsAbbr: "冲撞减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 6,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 15,
                materialType: MaterialType.MATERIAL_TYPE_BEAST,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_charge", type: 0 },
            },
            VerticalResist: {
                id: "VerticalResist",
                idx: 34,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "陨石伤害减轻",
                nameChsAbbr: "陨石减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 4,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 10,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_meteor", type: 0 },
            },
            BreathResist: {
                id: "BreathResist",
                idx: 35,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "地面伤害减轻",
                nameChsAbbr: "地面减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 4,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 10,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_floor", type: 0 },
            },
            TranslationResist: {
                id: "TranslationResist",
                idx: 36,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "子弹伤害减轻",
                nameChsAbbr: "子弹减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 4,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 10,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_bullet", type: 0 },
            },
            WallResist: {
                id: "WallResist",
                idx: 37,
                enchantType: EnchantType.ENCHANT_TYPE_DEF,
                nameChsFull: "贴地伤害减轻",
                nameChsAbbr: "贴地减轻",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: false,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 4,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 10,
                materialType: MaterialType.MATERIAL_TYPE_WOOD,
                description: "",
                cyteriaMapping: { base: "reduce_dmg_bowling", type: 0 },
            },
            Hit: {
                id: "Hit",
                idx: 38,
                enchantType: EnchantType.ENCHANT_TYPE_HIT,
                nameChsFull: "命中",
                nameChsAbbr: "命中",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 2,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "accuracy", type: 0 },
            },
            HitRate: {
                id: "HitRate",
                idx: 39,
                enchantType: EnchantType.ENCHANT_TYPE_HIT,
                nameChsFull: "命中",
                nameChsAbbr: "命中",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "accuracy", type: 1 },
            },
            Flee: {
                id: "Flee",
                idx: 40,
                enchantType: EnchantType.ENCHANT_TYPE_FLEE,
                nameChsFull: "回避",
                nameChsAbbr: "回避",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 2,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "dodge", type: 0 },
            },
            FleeRate: {
                id: "FleeRate",
                idx: 41,
                enchantType: EnchantType.ENCHANT_TYPE_FLEE,
                nameChsFull: "回避",
                nameChsAbbr: "回避",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "dodge", type: 1 },
            },
            Aspd: {
                id: "Aspd",
                idx: 42,
                enchantType: EnchantType.ENCHANT_TYPE_SPEED,
                nameChsFull: "攻击速度",
                nameChsAbbr: "攻速",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 16,
                baseMaterialCost: 1.5,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "aspd", type: 0 },
            },
            AspdRate: {
                id: "AspdRate",
                idx: 43,
                enchantType: EnchantType.ENCHANT_TYPE_SPEED,
                nameChsFull: "攻击速度",
                nameChsAbbr: "攻速",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 5,
                materialType: MaterialType.MATERIAL_TYPE_CLOTH,
                description: "",
                cyteriaMapping: { base: "aspd", type: 1 },
            },
            Cspd: {
                id: "Cspd",
                idx: 44,
                enchantType: EnchantType.ENCHANT_TYPE_SPEED,
                nameChsFull: "咏唱速度",
                nameChsAbbr: "唱速",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: 10,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 16,
                baseMaterialCost: 1.5,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "cspd", type: 0 },
            },
            CspdRate: {
                id: "CspdRate",
                idx: 45,
                enchantType: EnchantType.ENCHANT_TYPE_SPEED,
                nameChsFull: "咏唱速度",
                nameChsAbbr: "唱速",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 5,
                materialType: MaterialType.MATERIAL_TYPE_MEDICINE,
                description: "",
                cyteriaMapping: { base: "cspd", type: 1 },
            },
            Critical: {
                id: "Critical",
                idx: 46,
                enchantType: EnchantType.ENCHANT_TYPE_CRITICAL,
                nameChsFull: "暴击率",
                nameChsAbbr: "暴击",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 5,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "critical_rate", type: 0 },
            },
            CriticalRate: {
                id: "CriticalRate",
                idx: 47,
                enchantType: EnchantType.ENCHANT_TYPE_CRITICAL,
                nameChsFull: "暴击率",
                nameChsAbbr: "暴击",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 10,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 20,
                basePotentialCost: 1,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 5,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "critical_rate", type: 1 },
            },
            CriticalDmg: {
                id: "CriticalDmg",
                idx: 48,
                enchantType: EnchantType.ENCHANT_TYPE_CRITICAL,
                nameChsFull: "暴击伤害",
                nameChsAbbr: "暴伤",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 3,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 16.5,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "critical_damage", type: 0 },
            },
            CriticalDmgRate: {
                id: "CriticalDmgRate",
                idx: 49,
                enchantType: EnchantType.ENCHANT_TYPE_CRITICAL,
                nameChsFull: "暴击伤害",
                nameChsAbbr: "暴伤",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 10,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 50,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "critical_damage", type: 1 },
            },
            FireKiller: {
                id: "FireKiller",
                idx: 50,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对火属性伤害",
                nameChsAbbr: "对火",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_fire", type: 0 },
            },
            EarthKiller: {
                id: "EarthKiller",
                idx: 51,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对地属性伤害",
                nameChsAbbr: "对地",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_earth", type: 0 },
            },
            WindKiller: {
                id: "WindKiller",
                idx: 52,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对风属性伤害",
                nameChsAbbr: "对风",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_wind", type: 0 },
            },
            WaterKiller: {
                id: "WaterKiller",
                idx: 53,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对水属性伤害",
                nameChsAbbr: "对水",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_water", type: 0 },
            },
            LightKiller: {
                id: "LightKiller",
                idx: 54,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对光属性伤害",
                nameChsAbbr: "对光",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_light", type: 0 },
            },
            DarkKiller: {
                id: "DarkKiller",
                idx: 55,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "对暗属性伤害",
                nameChsAbbr: "对暗",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 30,
                lowerLimitIncreaseInterval: 30,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: true,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "stronger_against_dark", type: 0 },
            },
            FireShield: {
                id: "FireShield",
                idx: 56,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗火属性",
                nameChsAbbr: "抗火",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "fire_resistance", type: 0 },
            },
            EarthShield: {
                id: "EarthShield",
                idx: 57,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗地属性",
                nameChsAbbr: "抗地",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "earth_resistance", type: 0 },
            },
            WindShield: {
                id: "WindShield",
                idx: 58,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗风属性",
                nameChsAbbr: "抗风",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "wind_resistance", type: 0 },
            },
            WaterShield: {
                id: "WaterShield",
                idx: 59,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗水属性",
                nameChsAbbr: "抗水",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "water_resistance", type: 0 },
            },
            LightShield: {
                id: "LightShield",
                idx: 60,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗光属性",
                nameChsAbbr: "抗光",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "light_resistance", type: 0 },
            },
            DarkShield: {
                id: "DarkShield",
                idx: 61,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT,
                nameChsFull: "抗暗属性",
                nameChsAbbr: "抗暗",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 15,
                lowerLimitIncreaseInterval: 15,
                attenuationThreshold: 20,
                basePotentialCost: 5,
                isWeaponDoublePotential: true,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 25,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "dark_resistance", type: 0 },
            },
            AntiVirus: {
                id: "AntiVirus",
                idx: 62,
                enchantType: EnchantType.ENCHANT_TYPE_SPECIAL,
                nameChsFull: "异常抗性",
                nameChsAbbr: "异抗",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: 60,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "ailment_resistance", type: 0 },
            },
            Guard: {
                id: "Guard",
                idx: 63,
                enchantType: EnchantType.ENCHANT_TYPE_SPECIAL,
                nameChsFull: "格挡回复",
                nameChsAbbr: "格挡回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "guard_regenerate", type: 0 },
            },
            GardPower: {
                id: "GardPower",
                idx: 64,
                enchantType: EnchantType.ENCHANT_TYPE_SPECIAL,
                nameChsFull: "格挡力",
                nameChsAbbr: "格挡力",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "guard_power", type: 0 },
            },
            Avoid: {
                id: "Avoid",
                idx: 65,
                enchantType: EnchantType.ENCHANT_TYPE_SPECIAL,
                nameChsFull: "闪躲回复",
                nameChsAbbr: "闪躲回复",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 60,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 5,
                basePotentialCost: 20,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 100,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "evasion_regenerate", type: 0 },
            },
            Hate: {
                id: "Hate",
                idx: 66,
                enchantType: EnchantType.ENCHANT_TYPE_SPECIAL,
                nameChsFull: "仇恨值",
                nameChsAbbr: "仇恨",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: true,
                isNegativePossible: true,
                upperLimitIncreaseInterval: 20,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: 15,
                basePotentialCost: 6,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: 1,
                baseMaterialCost: 33.5,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "aggro", type: 0 },
            },
            OriginalElement: {
                id: "OriginalElement",
                idx: 67,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT_ADDITION,
                nameChsFull: "原属性",
                nameChsAbbr: "原属性",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: false,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 10,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 150,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "?", type: 0 },
            },
            OtherElement: {
                id: "OtherElement",
                idx: 68,
                enchantType: EnchantType.ENCHANT_TYPE_ELEMENT_ADDITION,
                nameChsFull: "非原属性",
                nameChsAbbr: "非原属性",
                nameEnFull: "",
                nameEnAbbr: "",
                isPercentage: false,
                isNegativePossible: false,
                upperLimitIncreaseInterval: null,
                lowerLimitIncreaseInterval: null,
                attenuationThreshold: null,
                basePotentialCost: 100,
                isWeaponDoublePotential: false,
                isArmorDoublePotential: false,
                preAttenuationIncrement: 1,
                postAttenuationIncrement: null,
                baseMaterialCost: 150,
                materialType: MaterialType.MATERIAL_TYPE_MANA,
                description: "",
                cyteriaMapping: { base: "?", type: 0 },
            }
        };
    }

    /**
     * 根据属性ID获取属性配置
     * @param {string} id - 属性ID
     * @returns {Object|null} 属性配置对象
     */
    static getPropertyById(id) {
        const properties = this.getProperties();
        return properties[id] || null;
    }

    /**
     * 根据布偶的魔法书映射查找属性
     * @param {string} base - 布偶中的base值
     * @param {number} type - 布偶中的type值 (0=数值, 1=百分比)
     * @returns {string|null} 属性ID
     */
    static getPropertyIdBycyteriaMapping(base, type) {
        const properties = this.getProperties();
        for (const [id, prop] of Object.entries(properties)) {
            if (prop.cyteriaMapping && prop.cyteriaMapping.base === base && prop.cyteriaMapping.type === type) {
                return id;
            }
        }
        return null;
    }

    /**
     * 获取所有有布偶映射的属性列表
     * @returns {Array} 属性配置对象数组
     */
    static getBouhMappedProperties() {
        const properties = this.getProperties();
        return Object.values(properties).filter(prop => prop.cyteriaMapping !== null);
    }
}
